name: Create Android Preview Build

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: preview
